### PR TITLE
YT: Fix 403 errors

### PR DESCRIPTION
**Pull request by MichailiK**
This PR contains commits cherry-picked from sedmelluq/lavaplayer#631 & (minor) merge conflicts fixes. 

As stated by the "upstream" PR, this is a temporary fix & has not been thoroughly tested. I have gotten in touch with one person having 403 issues. They said that this patch seems to be ~~working~~ **partially** working for them. I haven't tested this patch much myself, nor do I encounter 403 issues myself. I would suggest testing this further with multiple people. I can provide a binary of JMusicBot with this patch applied, if desired.

Fixes jagrosh/musicbot#885

### CODE REVIEW

**Comment by adamhradil** [comment]
Could you send me the binary? I can test it and provide feedback.

**Comment by trollollol123** [comment]
Any progress with this? Every time I use skip it just stops playin music,.

**Comment by adamhradil** [comment]
What is stopping this right now? Any updates?

**Comment by adamhradil** [comment]
@MichailiK any update on this?

**Pull request closed without merging**
